image: gradle:7.4-jdk17-alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build-deploy:
  stage: build
  script:
    - gradle build publish -PnpclibAuthHeaderName=Job-Token -PnpclibAuthHeaderValue=${CI_JOB_TOKEN}
  artifacts:
    name: plugins-jar
    paths:
      - ./api/build/libs/*.jar
      - ./core/build/libs/*.jar
    expire_in: 7 days
