name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: API-jars
          path: api/build/libs/api-*.jar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Plugin-jars
          path: core/build/libs/npclib-*-all.jar
